INSERT INTO users VALUES(1, 'Ivan', 'Ivanov')
INSERT INTO users VALUES(2, 'Maksim', 'Smirnov')
INSERT INTO users VALUES(3, 'Anton', 'Anisimov')
INSERT INTO tasks VALUES(1, 2, 'Give me a pen')
INSERT INTO tasks VALUES(2, 2, 'Give me a table3')
INSERT INTO tasks VALUES(3, 1, 'Give me a table3')
INSERT INTO tasks VALUES(4, 3, 'Give me a table3')
INSERT INTO tasks VALUES(5, 2, 'Give me a table')
INSERT INTO tasks VALUES(6, 3, 'Give me a table3')
INSERT INTO tasks VALUES(7, 2, 'Give me a table4')